#!/bin/bash
set -e

##
# Custom config for seperate OS.
if test $# -eq 1 && test -e "$1"; then
    CONFIG="$1"
else
    >&2 echo "Usage: $0 <os.conf.yaml"
    exit 1
fi

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
